export const Questions = [
  {id : 1, question: "Lorem ipsum dolor sit amet enim?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 2, question: "Quisque lorem tortor fringilla sed?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 3, question: "Nulla imperdiet sit amet magna?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 4, question: "Aliquam erat ac ipsum?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 5, question: "Ut sagittis ipsum dolor quam?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 6, question: "Ut sagittis ipsum dolor quam?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 7, question: "Nulla imperdiet sit amet magna?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 8, question: "Aliquam erat ac ipsum?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."},
  {id : 9, question: "Ut sagittis ipsum dolor quam?" ,
  answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo."}
]